language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t mateusz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true -it mateusz/docker-react npm run test 
